firebase/quickstart-ios

- config/README.md
- messaging/README.md
> Fix doc link typo

- analytics/AnalyticsExample/PatternTabBarController.m
Based on dvorak feedback on the inlined snippet.
> Tabbing out inner dictionary better

- messaging/FCM/AppDelegate.m
I think and hope this is the last instance of "pring."  :)
> Fixing typo, "pring" > "print."

- database/DatabaseExampleSwift/NewPostViewController.swift
- database/DatabaseExampleSwift/PostDetailTableViewController.swift
- database/DatabaseExampleSwift/PostTableViewCell.swift
> Fix bad swift rename

- admob/AdMobExampleTests/ViewController_Private.h
Change-Id: I0edf5d5b8855869370709eb31ef4f863b1a37d58
> fix admob ios quickstart test

- messaging/MessagingExample.xcodeproj/project.pbxproj
- messaging/MessagingExample/AppDelegate.m
- messaging/MessagingExampleSwift/AppDelegate.swift
- messaging/MessagingExampleSwift/MessagingExampleSwift.entitlements
- Add both iOS 9 handlers to ensure messages are received on iOS 10
- Add iOS 10 handlers for tapped messages
> Add more FCM handlers

- messaging/MessagingExample/AppDelegate.m
- messaging/MessagingExampleSwift/AppDelegate.swift
- Add include for connecting to FCM when app becomes active.
- Add call to completion handler in didReceiveRemoteNotification.
> Add doc include for connecting to FCM

- messaging/MessagingExample/AppDelegate.m
- messaging/MessagingExampleSwift/AppDelegate.swift
> Add missing completion handlers calls

- admob/AdMobExample/ViewController.m
- admob/AdMobExampleTests/AdMobExampleTests.m
- database/DatabaseExample/PostDetailTableViewController.m
- database/DatabaseExample/PostListViewController.m
- storage/StorageExample/ViewController.m
> Fix code style

- authentication/AuthenticationExample/AppDelegate.h
- authentication/AuthenticationExample/AppDelegate.m
- authentication/AuthenticationExample/MainViewController.h
- authentication/AuthenticationExample/MainViewController.m
- authentication/AuthenticationExampleSwift/AppDelegate.swift
- authentication/AuthenticationExampleSwift/MainViewController.swift
Bug: 34150292
Bug: 33728673
Change-Id: I6fa174ab60eff0c958e66df3c6a1a301cd60664c
> organize Firebase Auth ios quickstart

- authentication/AuthenticationExample/MainViewController.m
- authentication/AuthenticationExampleSwift/MainViewController.swift
Action sheet style did not work on ipad
> Change UIAlertController style from action sheet to alert

- firestore/FriendlyEats/LocalCollection.swift
- firestore/FriendlyEats/RestaurantsTableViewController.swift
This matches the rest of the SDK.
To be landed once Firebase 4.4.0 is released.
> Rename FIRListenerRegistration to ListenerRegistration

- analytics/AnalyticsExample/FoodPickerViewController.m
- analytics/AnalyticsExample/PatternTabBarController.m
- analytics/AnalyticsExampleSwift/FoodPickerViewController.swift
- analytics/AnalyticsExampleSwift/PatternTabBarController.swift
- get rid of not needed synchronize calls;
- using stringForKey instead of valueForKey.
> Refactoring NSUserDefaults usage:

- database/DatabaseExample/PostDetailTableViewController.m
- database/DatabaseExample/PostListViewController.m
- database/DatabaseExample/SignInViewController.m
Adds missing call to super in viewWillAppear, viewWillDisappear, viewDidAppear in DatabaseExample
> Adds missing call to super

- database/DatabaseExample/PostDetailTableViewController.m
Adds one more else case with exception to stop static analyses complaining about method possibly returning nil
> Solves static analiser issue

- dynamiclinks/DynamicLinksExample/AppDelegate.m
Bug:
64800610
Tested:
Ensure App builds fine.
> [FDL] Added example handling for FDL dismiss link

- .opensource/project.json
- README.md
This will improve how the page appears on
https://firebaseopensource.com/projects/firebase/quickstart-ios/
> Configure for firebaseopensource.com

- messaging/MessagingExample/AppDelegate.m
The macro you defined won't work. Better check if that interface was defined for which os. Check that interface by Cmd+Click to see.
> Better solution for checking os version

- abtesting/ABTestingExample/ViewController.swift
There are 3 places in the code that need to be updated to the latest syntax of Swift4.
> Updated to Swift4's Syntax

- mlkit/MLKitExample/Base.lproj/Main.storyboard
Connect IBAction to detect button to show detect menu.
> fix mlkit sample detect button doesn't work

- performance/PerformanceExample/ViewController.m
- performance/PerformanceExampleSwift/ViewController.swift
added an extra task derived from AVAssetDownloadURLSession
> added AVFoundation task

- mlvision/MLVisionExampleObjc/CameraViewController.m
Fixes #490 
initializes the annotation view and corrects the capture session callback signature.
> Fix #490 make the Objective-C live view great again

- crashlytics/CrashlyticsExample.xcodeproj/project.pbxproj
Fixed CrashReporting  -> Crashlytics in several places
> Fixed Crashlytics project.pbxproj

- analytics/AnalyticsExample/Base.lproj/Main.storyboard
- analytics/AnalyticsExample/FoodPickerViewController.m
- analytics/AnalyticsExample/PatternTabBarController.m
- analytics/AnalyticsExampleSwift/FoodPickerViewController.swift
- analytics/AnalyticsExampleSwift/PatternTabBarController.swift
When navigation issues don't get in the way, exploration is enhanced.
> Re-arranged navigation to fix one-way trip to PatternTabBarController

- README.md
> Add --repo-update to pod install

- dynamiclinks/DynamicLinksExample/AppDelegate.m
- invites/InvitesExample/AppDelegate.m
Added a couple of #ifs around code that compiles only with iOS 12 so that previous iOS versions are still supported
> Added support for iOS versions < 12

- mlmodelinterpreter/MLModelInterpreterExampleObjC/ModelInterpreterManager.m
> Solves two static analyser issues in ModelInterpreterManager.m

- authentication/AuthenticationExampleSwift/EmailViewController.swift
by using guard instead of if where appropriate and weakening self in blocks to avoid retain circles
> Refactors EmailViewController.swift of AuthenticationExampleSwift

- authentication/AuthenticationExample/MainViewController.m
- authentication/README.md
Reverts firebase/quickstart-ios#649
> Revert "Enable Microsoft sign in."

- authentication/AuthenticationExample/MainViewController.m
- authentication/README.md
Reverts firebase/quickstart-ios#651
> Reenable "Enable Microsoft sign in."

- authentication/AuthenticationExample/MainViewController.m
We plan to remove the FIRMicrosoftAuthProviderID constant in Firebase SDK.
> Update provider id for Microsoft

- authentication/AuthenticationExample/AppDelegate.m
- authentication/AuthenticationExample/MainViewController.m
- authentication/AuthenticationExampleSwift/AppDelegate.swift
- authentication/AuthenticationExampleSwift/MainViewController.swift
- authentication/Podfile
- authentication/Podfile.lock
> Remove Twitter sign in in Auth samples.

- abtesting/Podfile
- admob/Podfile
- analytics/Podfile
- authentication/Podfile
- config/Podfile
- crashlytics/Podfile
- crashreporting/Podfile
- database/Podfile
- dynamiclinks/Podfile
- firestore/Podfile
- functions/Podfile
- languageid/Podfile
- messaging/Podfile
- mlmodelinterpreter/Podfile
- mlvision/Podfile
- performance/Podfile
- smartreply/Podfile
- storage/Podfile
Replace `pod 'Firebase/Core'` with the equivalent and now recommended `pod 'Firebase/Analytics'`
> Update Podfiles for Firebase/Analytics

- abtesting/ABTestingExample/AppDelegate.swift
- abtesting/ABTestingExample/ViewController.swift
This causes nightly CI testing to fail.
> Add explicit UIKit imports.

- authentication/AuthenticationExample/MainViewController.m
- authentication/AuthenticationExampleSwift/MainViewController.swift
Ported to ObjC and pending merge once console and SDK support land.
Travis is currently failing on Podfile changes, which will be fixed once nonce support is released.
> Add Sign In with Apple

- abtesting/ABTestingExample.xcodeproj/project.pbxproj
- abtesting/ABTestingExampleUITests/ABTestingExampleUITests.swift
Consolidate internal and external UITests
I'll follow with PRs for the other tests.
> Consolidate ABTesting UITests

- crashlytics/CrashlyticsExample.xcodeproj/project.pbxproj
- crashlytics/CrashlyticsExample/ViewController.m
- crashlytics/CrashlyticsExampleSwift/ViewController.swift
- crashlytics/Podfile
- crashlytics/Podfile.lock
> [WIP] Update crashlytics sample for Crashlytics 4

- inappmessaging/Podfile
- scripts/prereq_core.sh
- update FIAM Podfile to reflect changes from https://github.com/firebase/firebase-ios-sdk/pull/4705
> FIAM - bump min iOS version to 9.0

- scripts/check_secrets.sh
- scripts/install_prereqs/abtesting.sh
- scripts/install_prereqs/admob.sh
- scripts/install_prereqs/analytics.sh
- scripts/install_prereqs/authentication.sh
- scripts/install_prereqs/config.sh
- scripts/install_prereqs/crashlytics.sh
- scripts/install_prereqs/database.sh
- scripts/install_prereqs/dynamiclinks.sh
- scripts/install_prereqs/firestore.sh
- scripts/install_prereqs/functions.sh
- scripts/install_prereqs/inappmessaging.sh
- scripts/install_prereqs/messaging.sh
- scripts/install_prereqs/performance.sh
- scripts/install_prereqs/storage.sh
- scripts/prereq_core.sh
- scripts/test.sh
- Single script for checking if secrets are available
- Use dot invocation to minimize passing environment variables around
> Simplify CI environment

- admob/AdMobExample/AppDelegate.m
- admob/AdMobExample/Info.plist
- admob/AdMobExampleSwift/AppDelegate.swift
- admob/Podfile
- admob/Podfile.lock
> Update admob sample

- storage/Podfile
- storage/Podfile.lock
- storage/README.md
- storage/StorageExampleSwift/DownloadViewController.swift
- storage/StorageExampleSwift/ViewController.swift
Update Storage Swift Example to use the FirebaseStorageSwift and the Result type APIs it provides.
Add a note to the README that the new APIs are still beta.
> Use new FirebaseStorageSwift pod

- config/ConfigExample.xcodeproj/project.pbxproj
- scripts/add_framework_script.rb
This is to help xcproject add framework automatically.
> Add framework tool

- scripts/add_framework_script.rb
This is to add libc++.dylib file for authentication quickstart.
> Add dylib file to project.

- authentication/README.md
just a small fix of a folder name. the link was working, just the displayed name was incorrect
> fix small error in auth readme

- config/LegacyConfigQuickstart/ConfigExample/ViewController.m
- config/LegacyConfigQuickstart/ConfigExampleSwift/ViewController.swift
Update fetch methods, move away from deprecated ones.
> Update fetch methods for config

- authentication/README.md
just fix twitter login link url. (current 404 page)
> fix twitter login url

- analytics/README.md
One of the bash commands in the README needed changing. Now, it should be good!
> Fixed bash command in README

- authentication/AuthenticationExample/ViewControllers/AuthViewController.swift
- authentication/README.md
> Make instructions more robust to code changes

- appdistribution/AppDistributionExample/AppDistributionViewController.swift
Updating the debug print statement to be more meaningful.
> Update print statement

- abtesting/ABTestingExample/ViewController.swift
This quickstart was failing to build with the latest firebase-ios-sdk master
> Stop using deprecated RC API

- installations/InstallationsExampleSwift/ViewController.swift
- scripts/test.sh
Enable pre-release Firebase 7 testing
> Firebase 7 specific code

- scripts/test.sh
> Both places in script

- config/Podfile
> Replace smart quotes in Podfile

- abtesting/ABTestingExample/ViewController.swift
- firestore/README.md
Googlers: for context see http://b/176971059
> Cloud Firestore --> Firestore

- functions/FunctionsExample/CommentCell.m
- functions/FunctionsExampleSwift/CommentCell.swift
> Fix bad data handling on client

- messaging/MessagingExample/AppDelegate.m
- messaging/MessagingExampleSwift/AppDelegate.swift
> Omit gcm message key in snippets

- firestore/Podfile.lock
Update Firestore Podfile since the zip nightly has been broken the last few nights
> Update Firestore Podfile.lock

- firestore/FirestoreExample.xcodeproj/project.pbxproj
This should fix the nightly test regression from #1127 discussed at https://github.com/firebase/firebase-ios-sdk/issues/7726
cc: @racheldoshcollins
> Deintegrate Firestore Xcode project

- firestore/FirestoreExample.xcodeproj/project.pbxproj
- firestore/FirestoreSwiftUIExample/Model/Restaurant.swift
- firestore/FirestoreSwiftUIExample/Model/Review.swift
- firestore/FirestoreSwiftUIExample/ViewModels/RestaurantViewModel.swift
- firestore/FirestoreSwiftUIExample/Views/RestaurantDetailView.swift
- firestore/FirestoreSwiftUIExample/Views/RestaurantImageView.swift
- firestore/FirestoreSwiftUIExample/Views/RestaurantListView.swift
- firestore/FirestoreSwiftUIExample/Views/ReviewView.swift
- firestore/FirestoreSwiftUIExample/Views/StarsView.swift
Adds RestaurantDetailView to displays reviews for an individual restaurant.
I successfully deintegrated this time :)
> Adding DetailView SwiftUI to firestore sample

- firestore/FirestoreExample.xcodeproj/project.pbxproj
- firestore/FirestoreSwiftUIExample/Extensions/Restaurant+Extension.swift
- firestore/FirestoreSwiftUIExample/ViewModels/RestaurantViewModel.swift
- firestore/FirestoreSwiftUIExample/Views/RestaurantDetailView.swift
- firestore/FirestoreSwiftUIExample/Views/RestaurantHeaderView.swift
- firestore/FirestoreSwiftUIExample/Views/StarsView.swift
- firestore/FirestoreSwiftUIExample/Views/WriteReviewView.swift
Implementing the "add review" screen of the Firestore sample app for SwiftUI architecture
> Adding AddReviewView for SwiftUI Firestore sample

- abtesting/Podfile
- abtesting/Podfile.lock
And 7.11.0 Podfile.lock update
> Update Podfile for IID removal

- abtesting/Podfile.lock
- admob/Podfile.lock
- analytics/Podfile.lock
- appdistribution/Podfile.lock
- authentication/Podfile.lock
- config/Podfile.lock
- crashlytics/Podfile.lock
- database/Podfile.lock
- dynamiclinks/Podfile.lock
- firestore/Podfile.lock
- functions/Podfile.lock
- inappmessaging/Podfile.lock
- installations/Podfile.lock
- messaging/Podfile.lock
- performance/Podfile.lock
- storage/Podfile.lock
For Firebase 7.11.0 and GoogleUtilities 7.4.0
> Update all the Podfile.lock's

- analytics/AnalyticsExample/BlogViewController.swift
Builds on [Travis](https://travis-ci.org/github/firebase/quickstart-ios/jobs/768748543#L1109) ✅
> Remove deprecated method from qs

- crashlytics/CrashlyticsExampleSwift/AppDelegate.swift
- crashlytics/CrashlyticsExampleSwift/ViewController.swift
- crashlytics/Podfile
Add a variety of common custom keys stored on iOS that can help developers better diagnose their crashes.
> Add examples of custom keys

- functions/FunctionsExample/CommentCell.m
- functions/FunctionsExampleSwift/CommentCell.swift
See https://github.com/firebase/quickstart-js/blob/master/functions/functions/index.js#L95
> Update quickstart to align with quickstart-js

- .travis.yml
- functions/FunctionsExampleSwift/CommentCell.swift
> Fix build breakage

- firestore/FirestoreExample.xcodeproj/project.pbxproj
- firestore/FirestoreSwiftUIExample/Extensions/Restaurant+Extension.swift
- firestore/FirestoreSwiftUIExample/ViewModels/RestaurantListViewModel.swift
- firestore/FirestoreSwiftUIExample/Views/FilterView.swift
- firestore/FirestoreSwiftUIExample/Views/PriceView.swift
- firestore/FirestoreSwiftUIExample/Views/RestaurantListView.swift
Adding filtering functionality to SwiftUI Firestore sample app
> Firestore sample app SwiftUI filtering

- database/DatabaseExample/PostDataSource.h
- database/DatabaseExample/PostListViewController.h
- database/DatabaseExampleSwift/PostDataSource.swift
- database/DatabaseExampleSwift/PostListViewController.swift
- database/Podfile
- database/Podfile.lock
- firestore/FirestoreExample/RestaurantDetailViewController.swift
- firestore/FirestoreExample/RestaurantsTableViewController.swift
- firestore/Podfile
- firestore/Podfile.lock
- functions/FunctionsExample/AppDelegate.m
- functions/FunctionsExample/FAuthPickerViewController.h
- functions/FunctionsExample/SignInViewController.h
- functions/FunctionsExample/SignInViewController.m
- functions/FunctionsExampleSwift/AppDelegate.swift
- functions/FunctionsExampleSwift/FAuthPickerViewController.swift
- functions/FunctionsExampleSwift/SignInViewController.swift
- functions/Podfile
- functions/Podfile.lock
> Pin FirebaseUI version and fix breakage

- scripts/framework_test.sh
Necessary for https://github.com/firebase/firebase-ios-sdk/pull/8338
> Add missing LEGACY check

- .github/workflows/abtesting.yml
- abtesting/ABTestingExample.xcodeproj/project.pbxproj
- abtesting/Tests_iOS/Tests_iOS.swift
Add UI tests for SwiftUI version of A/B Testing Quickstart. Currently only testing static UI independent of A/B Testing & Remote Config functionality.
> Add UI tests to abtesting [SwiftUI]

- abtesting/Shared/ContentView.swift
- abtesting/Tests_iOS/Tests_iOS.swift
Update app config from RemoteConfig using refreshable View modifier for iOS 15. Modularize ContentView with use of new struct BasicList. Add dynamic UI tests for refreshing functionality.
Any suggestions on how/whether to implement async/await functionality for this Quickstart?
> Add pull-down refreshing functionality on iOS 15 to abtesting [SwiftUI]

- abtesting/Shared/AppConfig.swift
Refactor app to use fetchAndActivate and `@MainActor`.
> Refactor abtesting with updated API usage

- authentication/AuthenticationExample/ViewControllers/AccountLinkingViewController.swift
- authentication/AuthenticationExample/ViewControllers/AuthViewController.swift
- authentication/LegacyAuthQuickstart/AuthenticationExample/AppDelegate.h
- authentication/LegacyAuthQuickstart/AuthenticationExample/AppDelegate.m
- authentication/LegacyAuthQuickstart/AuthenticationExample/MainViewController.m
- authentication/LegacyAuthQuickstart/AuthenticationExampleSwift/AppDelegate.swift
- authentication/LegacyAuthQuickstart/AuthenticationExampleSwift/MainViewController.swift
- authentication/LegacyAuthQuickstart/Podfile.lock
- authentication/LegacyAuthQuickstart/README.md
- authentication/Podfile.lock
> Update Auth examples with GoogleSignIn 6.0.0

- database/DatabaseExampleSwiftUI/DatabaseExample/DatabaseExample.xcodeproj/project.pbxproj
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Models/Post.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Models/PostViewModel.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Models/UserViewModel.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/MyPostsView.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/NewPostsView.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/PostCell.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/PostDetailView.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/RecentPostsView.swift
- fetch "My Posts" reload after logout/login
- added starDictionary variable and didTapStarButton function
- TODO: initialize variables in PostCell
> RTDB Star feature implementation

- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Models/PostViewModel.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Models/UserViewModel.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/ContentView.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/LoginView.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/MyPostsView.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/NewPostsView.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/PostCell.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/RecentPostsView.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/TopPostsView.swift
- added my top posts view
- fixed refresh error between different tabs that occurs when starring a post or creating a new post
> Implement My Top Posts View

- .github/workflows/config.yml
- config/ConfigExample.xcodeproj/project.pbxproj
- config/ConfigExample/ConfigExample.entitlements
- config/ConfigExample/RemoteConfigViewController.swift
- config/ConfigExample/SceneDelegate.swift
- config/Podfile
- config/README.md
This is what the Catalyst app looks like: (The window is resizable. There is a minimum size.)
<details>
<summary>See here</summary>
[
](url)
</details>
> Add iPad and Catalyst support for Config quickstart

- authentication/LegacyAuthQuickstart/README.md
- authentication/README.md
Add more instruction on how to navigate to Firebase service accounts  in Google Cloud Console.
> update Custom Authentication Setup documentation

- authentication/LegacyAuthQuickstart/AuthenticationExampleSwift/MainViewController.swift
Output of running ./scripts/style.sh on #1248
> style-fixes

- .github/workflows/abtesting.yml
- scripts/test_spm.sh
`test_spm.sh` is only being tested against A/B Testing in this PR
> Create CI build script for spm quickstarts

- .github/workflows/database.yml
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/PostDetailView.swift
> rtdb code cleanup

- .github/workflows/crashlytics.yml
- crashlytics/CrashlyticsExample.xcodeproj/project.pbxproj
- crashlytics/CrashlyticsExample.xcodeproj/xcshareddata/xcschemes/CrashlyticsExample (iOS).xcscheme
- crashlytics/CrashlyticsExample.xcodeproj/xcshareddata/xcschemes/CrashlyticsExample (macOS).xcscheme
- crashlytics/CrashlyticsExample.xcodeproj/xcshareddata/xcschemes/CrashlyticsExample (tvOS).xcscheme
- crashlytics/CrashlyticsExample.xcodeproj/xcshareddata/xcschemes/CrashlyticsExample (watchOS) (Complication).xcscheme
- crashlytics/CrashlyticsExample.xcodeproj/xcshareddata/xcschemes/CrashlyticsExample (watchOS) (Notification).xcscheme
- crashlytics/CrashlyticsExample.xcodeproj/xcshareddata/xcschemes/CrashlyticsExample (watchOS).xcscheme
- crashlytics/CrashlyticsSwiftUIExample_(watchOS)_Extension/Info.plist
- crashlytics/Info.plist
- crashlytics/Shared/UITests.swift
> Add UI Tests for Crashlytics

- .github/workflows/database.yml
- database/DatabaseExampleSwiftUI/DatabaseExample/DatabaseExample.xcodeproj/project.pbxproj
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/UITests.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/ContentView.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/LoginView.swift
- database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/SignUpView.swift
> Add UI Tests to rtdb

- crashlytics/CrashlyticsExample.xcodeproj/project.pbxproj
- crashlytics/Shared/ContentView.swift
- crashlytics/Shared/CrashlyticsSwiftUIExampleApp.swift
- add async await
- cleanup init() function with helper functions
> Add Async/Await to Crashlytics

- crashlytics/Shared/ContentView.swift
- update .onAppear modifier to .task modifier for (iOS 15, tvOS 15, macOS 12, watchOS 8, *)
- ensure fallback on earlier versions execute correctly
> Crashlytics Async/Await Update

- database/README.md
- typos fixed
- the link to rules fixed
> RTDB README changes

- appdistribution/Podfile
- appdistribution/Podfile.lock
- inappmessaging/Podfile
- inappmessaging/Podfile.lock
#1343 did not update the beta product Podfiles correctly. This PR fixes that.
> Fix beta product Podfile regression

- firestore/Podfile.lock
> Update Firestore Podfile.lock to latest

- storage/LegacyStorageQuickstart/StorageExample.xcodeproj/project.pbxproj
Might fix https://github.com/firebase/firebase-ios-sdk/issues/9534 introduced by #1363
> Remove GoogleService-Info.plist from test targets

- config/ConfigExample/JSON Recipes/peanut_butter_and_jelly.json
- config/ConfigExample/JSON Recipes/salad.json
- config/ConfigExample/JSON Recipes/sugar_cookies.json
See https://github.com/firebase/quickstart-ios/blob/master/config/ConfigExample/RemoteConfigViewController.swift#L141-L148
> Decodable expecting Int for some fields

- .github/workflows/authentication.yml
See https://github.com/firebase/quickstart-ios/actions/runs/3561267753
> Fix broken yml file

- authentication/AuthenticationExample/ViewControllers/AccountLinkingViewController.swift
- authentication/AuthenticationExample/ViewControllers/AuthViewController.swift
- authentication/LegacyAuthQuickstart/AuthenticationExample/MainViewController.m
- authentication/LegacyAuthQuickstart/Podfile.lock
- authentication/Podfile
- authentication/Podfile.lock
Fix #1461
Update Auth Quickstarts to GSI 7.x API
More work is still needed to use the recommended Info.plist configuration approach instead of code-based configuration
> Update to GSI 7 API

- authentication/AuthenticationExample/AppDelegate.swift
- authentication/AuthenticationExample/ViewControllers/AuthViewController.swift
> Add snippets for Google Sign-In v7.0.0 changes

- .github/workflows/authentication.yml
- authentication/AuthenticationExample.xcodeproj/project.pbxproj
- authentication/AuthenticationExample/ViewControllers/AuthViewController.swift
- authentication/Podfile.lock
This is the quick start that demonstrates how to use the new API in https://github.com/firebase/firebase-ios-sdk/pull/10068
> Use new appleCredential API to set user’s full name when signing in with Apple

- functions/FunctionsExample/FunctionsExample.xcodeproj/project.pbxproj
- functions/FunctionsExample/Shared/FunctionsExampleApp.swift
- functions/FunctionsExample/Shared/View/AddNumbersView.swift
- functions/FunctionsExample/Shared/View/CapitalizeMessageView.swift
- Updated Firebase versioning constraints
- Removed unneeded imports
- Removed unused libraries
> [Functions] Update to depend on latest Firebase major version

- storage/LegacyStorageQuickstart/StorageExample.xcodeproj/project.pbxproj
- storage/LegacyStorageQuickstart/StorageExample/Placeholder.swift
To see if it addresses issues like the `redefinition of module 'SwiftBridging'` in https://github.com/firebase/firebase-ios-sdk/actions/runs/7908402675/job/21587502678
It might actually be a GHA configuration issue though:
https://forums.developer.apple.com/forums/thread/739510
> Add Swift placeholder

- scripts/add_framework_script.rb
Reverts firebase/quickstart-ios#1577
> Revert "Revert "[Infra] Embed frameworks `scripts/add_framework_script.rb`""

- vertexai/README.md
Added a README for the Vertex AI for Firebase SDK.
> [Vertex AI] Add a README with a link to the sample app

- crashlytics/Shared/ReachabililtyHelper.swift
> [Infra] Fix warnings in crashlytics/Shared/ReachabililtyHelper.swift

- database/Podfile
- database/Podfile.lock
- firestore/Podfile
- firestore/Podfile.lock
- functions/LegacyFunctionsQuickstart/Podfile
- functions/LegacyFunctionsQuickstart/Podfile.lock
Update to a FirebaseUI compatible with the Firebase 11 minimum version support.
> Update to Firebase UI 14

- authentication/AuthenticationExample/SceneDelegate.swift
Corresponding sample app update: https://github.com/firebase/firebase-ios-sdk/pull/13557
> [Auth] When swizzling is disabled, open URLs via SceneDelegate

- .github/workflows/authentication.yml
- authentication/Podfile.lock
- firestore/Podfile.lock
- scripts/test.sh
Companion to https://github.com/firebase/firebase-ios-sdk/pull/13745
> Update CI to Xcode 16

- scripts/build-for-testing.sh
Steps:
1. Merge
2. Test Firebase FTL workflow
3. If it doesn't work, revert.
> [Infra] Update build-for-testing.sh

- firebaseai/FirebaseAIExample.xcodeproj/project.pbxproj
This should update to a release when 10.13.0 is out
> [firebase-ai] Update qs to use firebase-ios-sdk main

- inappmessaging/InAppMessagingExample/AppDelegate.m
- inappmessaging/InAppMessagingExampleSwift/AppDelegate.swift
- inappmessaging/Podfile
- inappmessaging/Podfile.lock
- swiftui/PasswordlessSwiftUI/Podfile
- swiftui/PasswordlessSwiftUI/Podfile.lock
I'm not seeing any doc site snippet comments near the deleted code, so this should be gtg.
> [Infra] Remove FDL references from other quickstarts
