firebase/quickstart-ios

messaging/FCMSwift/AppDelegate.swift

Renamed the function tokenRefreshNotificaiton to
tokenRefreshNotification.

Fixes a typo in a function name

---

admob/AdMobExample/ViewController.m

Previously if a network request failed the interstitial button would stop working.

add error handling to sample

---

messaging/FCMSwift/AppDelegate.swift

We had a client project using the FCM on iOS 9 and everything worked fine. The push notifications always got through fantastically. But after updating the project to use Swift 3 and updating one of our test devices to iOS 10, suddenly the app didn't receive any push notifications when it was on background.
We struggled with this for a couple days, but then figured out after comparing the Objective C and Swift sample logic. The solution was embarrassingly simple.
[As seen here](https://github.com/firebase/quickstart-ios/blob/master/messaging/FCM/AppDelegate.m#L85), the Objective C sample for messaging has different behavior than the Swift one. The ```registerForRemoteNotifications``` function is called for **every iOS version above 7.1** (including iOS 10), but on the Swift sample it's …

[Swift sample] Fix for FCM notifications not going through on iOS 10 when app is in background

---

database/DatabaseExampleSwift/SignInViewController.swift

When I was first learning the ins and outs of Firebase, I came here to get a real-world, full example of how the Firebase code worked.
However, I was appalled at what I saw. 13 levels of indentation? **13**!?
And most were just nested `if let` statements -- not a `guard` anywhere to be found.
This pull request is my attempt at turning at least one of the classes into a more readable example, with added comments to explain what is going on (hopefully more helpful to a beginner) and with some pieces of code broken up into bite-sized functions. 
Note: the spinner code probably isn't implemented properly. I can't figure out why you'd call a hideSpinner *closure* inside the startSpinner closure. In particular, a [certain progress indicator …

Attempt to make Swift sign in code easier to read

---

messaging/FCM/FCM.entitlements
messaging/FCMSwift/FCMSwift.entitlements
messaging/README.md

XCode 8 requires explicit entitlements for remote notifications.

Add explicit Entitlements for APNs required by XCode 8

---

messaging/FCM/AppDelegate.m
messaging/FCMSwift/AppDelegate.swift

To help with debugging added APNs functions, when swizzling is enabled they are not required however when swizzling is off they are.

Add APNs functions

---

messaging/MessagingExample/AppDelegate.m
messaging/MessagingExampleSwift/AppDelegate.swift

- Move iOS 10 data message handler into its own block so it is not
confused with notification message handlers.

Identify iOS 10 data message handler

---

messaging/MessagingExample/AppDelegate.m
messaging/MessagingExampleSwift/AppDelegate.swift

Avoid crashes if non FCM messages, those without a message ID, are received.

Add check for message ID

---

messaging/MessagingExample/AppDelegate.m

The delegates are properties, not methods, so they must be accessed
using dot notation.

Fix code style

---

messaging/MessagingExample/AppDelegate.m
messaging/MessagingExampleSwift/AppDelegate.swift
messaging/README.md

This sample registers for remote notifications on first run,
if this is not desirable it should be moved to a more appropriate
place so the dialog is shown at a more appropriate time.
Resolves #184

Add note about notification permission dialog

---

messaging/MessagingExample/AppDelegate.m
messaging/MessagingExampleSwift/AppDelegate.swift

Prior to this, when running the Example app for the first time, the
following error was being printed in the console:
Unable to connect to FCM. Error Domain=com.google.fcm Code=501 "(null)"
After accepting the notifications permission, the following error was
being printed in the console:
Unable to connect to FCM. Error Domain=com.google.fcm Code=2001 "(null)"
The first error means that the app tried to connect to FCM while there
was no Firebase registration token available. It now checks for the
current token and exits early if it's null.
The second error means that the app tried to connect to FCM while
another connection is already available. It now disconnects from any
existing connection prior to trying to connect again.
The better solution would be to have an `isConnected` property …

Fix incorrect FCM connection logic

---

messaging/MessagingExample/AppDelegate.m
messaging/MessagingExampleSwift/AppDelegate.swift

Delegate should set before asynchronous `requestAuthorizationWithOptions`. It fixes #194.

Fix receiving push notification on iOS 10

---

messaging/MessagingExample/AppDelegate.m
messaging/MessagingExampleSwift/AppDelegate.swift

This updates the sample with some subtle changes in the 2.0.0 SDK that we missed during the initial docs update:
1. It updates the comment about setting the APNs token directly with Messaging instead of InstanceID
2. It adds commented-out lines to show where appDidReceiveMessage: is supposed to be called (similar to the commented-out line about setting the APNs token if swizzling is disabled
3. It adds the iOS 10 delegate handler for data messages, to serve as an example for developers following the app as a template for their own apps

Update Messaging samples for subtle 2.0.0 SDK changes

---

messaging/MessagingExample/AppDelegate.m
messaging/MessagingExampleSwift/AppDelegate.swift

This helps us avoid a potential race condition where iOS could return an APNs token before Firebase (and FIRMessaging) has been configured, potentially not associating the APNs token with the FCM token.

Call configure before registering w/ notifications

---

database/DatabaseExampleSwift/Post.swift

Hi, I've found an issue with the Swift version of the DatabaseExample. The Snapshot parsing was not working properly because it couldn't transform the response into a [String:String] dictionary. The fix was rather simple, I just parsed the snap response into a [String:AnyObject] dictionary and included the starCount value in the response (it was not included so the number of stars of a given comment was always zero).

Fix Firebase Snapshot parsing on swift 4 - xcode 9

---

performance/PerformanceExampleSwift/ViewController.swift

Bringing of String to NSString is not toll free.

Get rid of not needed casting to NSString

---

messaging/MessagingExample/AppDelegate.m
messaging/MessagingExampleSwift/AppDelegate.swift

On each app startup and whenever the token changes
didReceiveRegistrationToken is fired. This is the
recommended way of being updated about the most
current FCM registration token.
Merge this PR only when a pod including [this change](https://github.com/firebase/firebase-ios-sdk/commit/2b40693be4c9aa2c94b668fb144c6993f557b8d6) is available.

Use FCM didReceiveRegistrationToken

---

performance/PerformanceExample/ViewController.m

If file is read in NSUTF8StringEncoding, I don't think it's right to write it in NSStringEncodingConversionAllowLossy.

Fixes encoding.

---

mlkit/MLKitExample/ViewController.swift

To show image more clearly, multiply device screen scale to image view size.
Before:
After:

[MLKit] multiplied device screen scale

---

messaging/MessagingExample/AppDelegate.m
messaging/MessagingExample/Base.lproj/Main.storyboard
messaging/MessagingExample/ViewController.h
messaging/MessagingExample/ViewController.m
messaging/MessagingExampleSwift/AppDelegate.swift
messaging/MessagingExampleSwift/ViewController.swift

for automation purposes we'd like to display FCM tokens on UI:
- when it's initially received
- when it's requested via [FIRMessaging messaging].FCMToken
- when it's requested via  [[FIRInstanceID instanceID] instanceIDWithHandler:
implemented for both ObjC and Swift apps

Added labels that display FCM tokens

---

authentication/AuthenticationExampleSwift/EmailViewController.swift

Updated the create_user snippet to include a line showing how to access the user from the `authResult` object. I suggest this based upon multiple developers on SO who have been confused and thought `authResul`t was itself of type `User` instead of `AuthDataResult`. Here are a couple examples of this confusion:
https://stackoverflow.com/questions/51589895/value-of-type-authdataresult-has-no-member-providerid-firebase-5-0/51600266#51600266
https://stackoverflow.com/questions/51409307/firebase-swift-4-authdataresult-eror/51409688#51409688
While the function itself doesn't then use the "user" created, the snippet will appear in the guides, so I think it's worth it to prevent some further confusion. If you have suggestions for other ways we could demonstrate this in the code, I'm up for …

Updated the create_user snippet 

---

inappmessaging/InAppMessagingExample.xcodeproj/project.pbxproj

Changed  IPHONEOS_DEPLOYMENT_TARGET to 11.2 for InAppMessaging quickstart app so that it's consistent with all other quickstart apps

changed IPHONEOS_DEPLOYMENT_TARGET to 11.2

---

authentication/AuthenticationExample/MainViewController.m

This makes Objective-C authentication example work reasonably and match Swift example.

Comments out line which is supposed to be commented out.

---

firestore/FirestoreExampleUITests/FirestoreUITest.m

The testApplyFilter test assumes that there are a fixed number of
restaurants with the category Deli, and verifies that applying a filter
returns the right number of restaurants.
Unfortunately, the actual data behind this is random, and depends
entirely on the current state of the data in a shared project. If anyone
adds additional restaurants it's possible to add/remove Delis because
the client only loads the first 50 restaurants.
Tracked in b/147740878.

Temporarily disable flaky firestore/testApplyFilter test

---

crashlytics/CrashlyticsExample.xcodeproj/project.pbxproj

We had an issue where manual testers couldn't figure out why there was a build error here (following this [README](https://github.com/firebase/firebase-ios-sdk/blob/master/ZipBuilder/Template/README.md)). The reason was that the run script in the quick start is configured to look for the cocoapods path. Hopefully this change will make integrating via zip install easier.
Here's the content in human-readable form:
```
if test -f "${PODS_ROOT}/FirebaseCrashlytics/run"; then
"${PODS_ROOT}/FirebaseCrashlytics/run"
elif test -f "${PROJECT_DIR}/run"; then
"${PROJECT_DIR}/run"
elif test -f "${PROJECT_DIR}/FirebaseCrashlytics/run"; then
"${PROJECT_DIR}/FirebaseCrashlytics/run"
else
echo 'error: Could not find path to Crashlytics "run" script. Please ensure you have included the Crashlytics "run" …
```

Update Crashlytics run script to handle zip installs

---

installations/InstallationsExample/AppDelegate.m
installations/InstallationsExample/ViewController.m
installations/InstallationsExampleSwift/AppDelegate.swift
installations/InstallationsExampleSwift/ViewController.swift
installations/Podfile
installations/Podfile.lock

See b/148639420 for rationale.
Strangely, the Installations sample doesn't have a Firebase.h in its Core headers after running `pod update`, so I was unable to remove the header import TODOs.

Remove explicit core from podfile

---

TestUtils/FIREGSignInHelper.m

UITests which do not activate a real keyboard will display a keyboard interface on the screen and this tap in app can hide the keyboard and do the rest. Otherwise, the Click Next will only hide the keyboard but not really click the next button and fails the test

Tap to hide keyboard before tapping next

---

abtesting/Podfile

Fix a new build failure with the latest RC - b/155290239
The better longer term fix would be to migrate the quickstart from InstanceID to Installations
Nightlies missed this failure because they automatically install all internal pods including Installations.

Fix ABT QS build failure with latest RC

---

messaging/MessagingExample/AppDelegate.m
messaging/MessagingExampleSwift/AppDelegate.swift

Fix #932 
Also return alert type in one of the display notification delegate to ensure notification can be displayed when app is in foreground. This might or might not be the reason of [#5519](https://github.com/firebase/firebase-ios-sdk/issues/5519) where users can't receive notification.

Remove deprecated mcs code

---

config/ConfigExample/ViewController.m
config/ConfigExampleSwift/ViewController.swift
config/Podfile.lock

Proposing to remove expirationDuration from the Remote Config getting started flow to simplify usability:
- It prevents console changes from being fetched
- Even after changing the value, the previous run's fetch is still locked in
- I can't think of a use case where I want to call fetch but only fetch old values

Remove expirationDuration

---

crashlytics/CrashlyticsExample.xcodeproj/project.pbxproj

This is the same as [Update Crashlytics run script to handle zip installs](https://github.com/firebase/quickstart-ios/pull/902) but for Swift quickstart. Zip framework testing is putting zip in "${PROJECT_DIR}/run".

Update Crashlytics run script to handle zip installs for swift quickstart.

---

scripts/add_framework_script.rb

Auth testapp request libc++.dylib from /usr/lib and accelerate.framework from xcode frameworks dir. These two cannot be copied to another folder and imported to the xcode project. This update will enable this tool to import a single file.
The argument/options update will increase the readability.
The test is done for [remote config in firebase-ios-sdk framework testing workflow](https://github.com/firebase/firebase-ios-sdk/runs/828632641?check_suite_focus=true)
scripts/setup_quickstart_framework.sh from firebase-ios-sdk repo depends on this file and will be updated whlie this pr is submitted. The change for the tested pr is [here](https://github.com/firebase/firebase-ios-sdk/pull/5958/files).

Update Add Framework script

---

messaging/MessagingExample/AppDelegate.m
messaging/MessagingExampleSwift/AppDelegate.swift

Fixes https://github.com/firebase/firebase-ios-sdk/issues/5625.

Fix missing messaging call in swizzling disabled snippets

---

dynamiclinks/DynamicLinksExampleSwift/AppDelegate.swift

Fixing Deeplink popup not coming when clicking an FDL and opening up the app using universal linking.
Code was not in place to handle and show the pop up when the app gets universal linked by clicking on an fdl.
-Added code to show the Deeplink pop up message when clicking an FDL and opening up the app using universal linking.

Fixing Deeplink popup not coming when clicking an FDL 

---

mock-GoogleService-Info.plist

Required to fix tests for https://github.com/firebase/firebase-ios-sdk/pull/6678

Change API key in mock-GoogleService-Info.plist to match valid format

---

firestore/Podfile
firestore/Podfile.lock
storage/Podfile
storage/Podfile.lock

With Firebase 7.x, beta versions must be explicit in the Podfile now that they're not using 0 major versions.
The Functions CI failure is unrelated and has been on master for several days.

Podfile updates for 7.x Swift pods

---

storage/StorageExampleUITests/StorageExampleUITests.m

The Photos UI has changed in the Xcode 12 simulators breaking the UI tests.
This PR disables the tests until a fix is made.
The Functions CI failure is addressed in #1072
Issue to reenable at #1073

Disable Storage UI Tests until they're updated for Xcode 12

---

functions/FunctionsExampleUITests/FunctionsExampleUITests.m

The extra validation introduced in Xcode 12 and iOS 14 breaks the sign in flow in the Functions test.
Disabling here until it can be reworked.
Issue to reenable at #1074

Skip Functions UITests until updated for Xcode 12

---

database/DatabaseExample.xcodeproj/project.pbxproj
database/Podfile
database/Podfile.lock

I think this is causing the quickstart tests to fail without running any tests in https://github.com/firebase/firebase-ios-sdk/pull/5916.
Example: https://github.com/firebase/firebase-ios-sdk/pull/5916/checks?check_run_id=1323797486

Deduplicate classes in test targets

---

firestore/Podfile.lock

The Firestore Quickstart test started failing after the GDT 8.3.0 update because it was still using GoogleUtilities 7.1.1 because of #1099.

Update Firestore Podfile.lock

---

functions/README.md

The StackOverlow link in the functions quickstart's README file was mistakenly pointing to Firebase Crash Reporting. This PR should point it to the correct url.

docs(functions): fix README's StackOverflow link

---

.travis.yml
messaging/MessagingExampleSwift/ViewController.swift
messaging/Podfile.lock

Address nightly build test failures https://github.com/firebase/firebase-ios-sdk/issues/7857
Fix Swift build regression from #1138 
Update Podfile.lock (a #1099) issue
Add build test to travis for Messaging Swift

Fix Messaging Swift build regression

---

abtesting/ABTestingExample/ViewController.swift
abtesting/Podfile.lock

Firebase 8 no longer includes FirebaseInstanceID in Firebase.h
This is a temporary fix for the resulting build failure, but the QuickStart should be migrated away from using IID.
More details in https://github.com/firebase/firebase-ios-sdk/issues/7921

Fix Firebase 8.x build failure

---

abtesting/ABTestingExample/ViewController.swift

A/B Test no longer depends on InstanceID, remove IID check in quickstart app. Replace with FIS ID check.

Remove instanceID from abtesting quickstart app

---

authentication/AuthenticationExample/AppDelegate.swift

Follow the steps in https://developers.facebook.com/docs/facebook-login/ios#delegate to initialize the `FBSDKCoreKit` SDK.
Previously, Facebook Login worked without this, but in `FBSDKCoreKit` v9.2.0 and later, it seems that the Facebook SDK needs to be explicitly initialized in order to properly access the values in `Info.plist`.

Explicitly initialize Facebook SDK.

---

firestore/FirestoreExampleUITests/FirestoreUITest.m
firestore/Podfile.lock

Double timeout to see if it addresses https://github.com/firebase/firebase-ios-sdk/issues/8159
Also, update Podfile.lock (#1099 workaround)

Increase Firestore UITest timeout

---

abtesting/ABTestingExample/ViewController.swift
abtesting/README.md

Add installation auth token logging to abtesting quickstart sample and accompanying instructions.

Add abtesting installation auth token usage

---

.github/workflows/abtesting.yml
abtesting/Shared/AppConfig.swift
abtesting/Shared/ContentView.swift

Use updateFromRemoteConfigAsync when using iOS 15 pull-down-to-refresh functionality.
Where else should async/await functionality be used? Should the app log something special to showcase async/await?

Add async/await functionality to abtesting [SwiftUI]

---

inappmessaging/InAppMessagingExampleSwift/AppDelegate.swift
inappmessaging/InAppMessagingExampleSwift/ViewController.swift

Should fix the [failure](https://github.com/firebase/firebase-ios-sdk/runs/3251416541?check_suite_focus=true) from https://github.com/firebase/firebase-ios-sdk/issues/8471#issuecomment-893449537.

FIAM: explicitly import modules used in Swift

---

database/DatabaseExampleSwiftUI/DatabaseExample/DatabaseExample.xcodeproj/project.pbxproj
database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Models/ScreenDimensions.swift
database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/ContentView.swift
database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/LoginView.swift
database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/NewPostsView.swift
database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/PostCell.swift
database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/PostDetailView.swift
database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/PostsView.swift
database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/SignUpView.swift
database/DatabaseExampleSwiftUI/DatabaseExample/tvOS/Info.plist
database/DatabaseExampleSwiftUI/DatabaseExample/tvOS/Preview Content/Preview Assets.xcassets/Contents.json

Add tvOS platform to RTDB

---

crashlytics/CrashlyticsExample.xcodeproj/project.pbxproj
crashlytics/CrashlyticsExample.xcodeproj/xcshareddata/xcschemes/CrashlyticsExample (watchOS) (Complication).xcscheme
crashlytics/CrashlyticsExample.xcodeproj/xcshareddata/xcschemes/CrashlyticsExample (watchOS) (Notification).xcscheme
crashlytics/CrashlyticsExample.xcodeproj/xcshareddata/xcschemes/CrashlyticsExample (watchOS).xcscheme
crashlytics/CrashlyticsSwiftUIExample_(watchOS)/Info.plist
crashlytics/CrashlyticsSwiftUIExample_(watchOS)_Extension/Info.plist
crashlytics/OUTLINE.md

Was using crashlytics qs to debug an issue and got a warning that the bundle ID didnt match with that in the default googleservice-info.plist. 
I did this with: 
```
grep -rl 'Google-LLC.CrashlyticsSwiftUIExample' . | xargs sed -i '' 's/Google-LLC.CrashlyticsSwiftUIExample/com.google.firebase.quickstart.CrashlyticsExample/'
```

Use common qs bundle ID format in Crashlytics qs

---

abtesting/Shared/AppConfig.swift
abtesting/Shared/ContentView.swift
crashlytics/Shared/ContentView.swift
database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Models/PostViewModel.swift
database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Views/PostCell.swift

More context at https://forums.swift.org/t/platform-and-version-wrapping-for-swift-concurrency/52269
Fixes the CI failures in #1300

Concurrency checks for Xcode 13 and macOS

---

storage/Podfile
storage/Podfile.lock
storage/StorageExample/AppDelegate.m
storage/StorageExample/DownloadViewController.m
storage/StorageExample/ViewController.m
storage/StorageExampleSwift/AppDelegate.swift
storage/StorageExampleSwift/DownloadViewController.swift
storage/StorageExampleSwift/ViewController.swift

More context at https://github.com/firebase/firebase-ios-sdk/issues/9074
The rest of this repo should be similarly updated.

Stop using Firebase umbrella pod in Storage quickstart

---

config/ConfigExample/RemoteConfigViewController.swift
config/ConfigExampleUITests/ConfigExampleUITests.swift
config/Podfile
config/Podfile.lock

Quickstart PR that accompanies https://github.com/firebase/firebase-ios-sdk/pull/9084 and the new type safe Swift Codable APIs for Remote Config
Now that 8.12.0 has released, this is functional with published podspecs.

Update RC JSON example to use new API

---

authentication/Podfile
authentication/Podfile.lock

Workaround missing Facebook SDK 13.0 support to fix CI until we do a quickstart update.
See CI failures like https://github.com/firebase/firebase-ios-sdk/runs/5320909827?check_suite_focus=true#step:5:917

Auth QS does not build with Facebook 13.0.0

---

firestore/FirestoreSwiftUIExample/ViewModels/RestaurantListViewModel.swift
firestore/Podfile.lock

See https://github.com/firebase/firebase-ios-sdk/pull/9101, internal b/222563260.
This change will cause build failures before Firebase dependencies are updated to 8.13.0.

Update quickstart for non-optional Codable

---

config/ConfigExample.xcodeproj/project.pbxproj

Remove the following `pod install` warning:
[!] The `ConfigExampleUITests [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-ConfigExample-ConfigExampleUITests/Pods-ConfigExample-ConfigExampleUITests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
- Use the `$(inherited)` flag, or
- Remove the build settings from the target.
[!] The `ConfigExampleUITests [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-ConfigExample-ConfigExampleUITests/Pods-ConfigExample-ConfigExampleUITests.release.xcconfig'. This can lead to problems with the CocoaPods installation
- Use the `$(inherited)` flag, or
- Remove the build …

Fix pod install warning

---

storage/LegacyStorageQuickstart/Podfile
storage/LegacyStorageQuickstart/Podfile.lock
storage/LegacyStorageQuickstart/StorageExampleSwift/DownloadViewController.swift

Updates to Storage Legacy Quickstart for v9. 
The Podfile `source` changes should be deleted after v9 releases and the v9 branch merges to master.

Storage QS updates for v9

---

functions/LegacyFunctionsQuickstart/Podfile
functions/LegacyFunctionsQuickstart/Podfile.lock

This was changed in the `v9` branch and merged to `master` in #1376.
I don't think it is needed though.

[Functions] Remove version pin for `FirebaseAnalytics`

---

firestore/FirestoreExample/NewReviewViewController.swift

Problem:
If a user tries to add a review in NewReviewViewController without being logged in, the app crashes. 
Because it tries to access the "uid" property of current user forcefully, that is nil without an authenticated user.
Solution:
So I added a guard statement to prevent this crash.
Also it is a bad practice in Swift to force unwrap optional

Added guard check for uid in "NewReviewViewController"

---

firestore/FirestoreExample.xcodeproj/project.pbxproj
firestore/FirestoreExample/FiltersViewController.swift
firestore/FirestoreExample/RestaurantsTableViewController.swift
firestore/FirestoreExample/UINavigationBar+Extension.swift

Applied a UINavigationBarAppearance to fix transparent navigation bars on iOS 15, which was causing the filter view navigation bar text to overlap the restaurant list view text.
UINavigationBar background colour behaviour changed in iOS 13 and iOS 15, as described in [TN3106: Customizing the appearance of UINavigationBar](https://developer.apple.com/documentation/technotes/tn3106-customizing-uinavigationbar-appearance).

Firestore: Fix transparent nav bar on iOS 13+

---

config/ConfigExample/RemoteConfigViewController.swift

when `typedRecipeKey` isn't defined or isn't the correct recipe format the app crashes

Print JSON decoding error instead of crashing app

---

abtesting/LegacyABTestingQuickstart/Podfile
admob/Podfile
analytics/LegacyAnalyticsQuickstart/Podfile
appdistribution/Podfile
authentication/LegacyAuthQuickstart/Podfile
config/LegacyConfigQuickstart/Podfile
crashlytics/LegacyCrashlyticsQuickstart/Podfile
database/Podfile
dynamiclinks/Podfile
functions/LegacyFunctionsQuickstart/Podfile
inappmessaging/Podfile
installations/Podfile
messaging/Podfile
performance/Podfile
storage/LegacyStorageQuickstart/Podfile
template/clone.sh

- Unblocks [firebase-ios-sdk/#10233](https://github.com/firebase/firebase-ios-sdk/pull/10233)
- #10233 bumps the min. supported versions for products. Some of the CI failures because the quickstart projects used to test them then have lower min. supported versions declared in their Podfile.

[Firebase 10] Sync project min. versions with product min. versions

---

database/DatabaseExample/NewPostViewController.m
database/DatabaseExampleSwift/NewPostViewController.swift

Updated the RTDB ObjC and Swift (UIKit) quickstarts to show an alert when attempting to post a new message missing a title or body. This makes them [consistent](https://github.com/firebase/quickstart-ios/blob/971254d94b4c8536176add666cfb0c1f71648050/database/DatabaseExampleSwiftUI/DatabaseExample/Shared/Models/PostListViewModel.swift#L42-L46) with the SwiftUI quickstart.

RTDB: Prevent blank new message posts

---

database/DatabaseExampleUITests/DatabaseExampleUITests.m

Updated the `testCreateNewValidPost` test in `DatabaseExampleUITests` to write text to the message body; PR #1451 enforced that the title and body could not be empty.

[RTDB] Fix testCreateNewValidPost UI test

---

dynamiclinks/DynamicLinksExample.xcodeproj/project.pbxproj

- Removed a reference to a deleted file named AppDelegate.swift from the Xcode project.
- Updated the DynamicLinksSwiftUIExample target to use the shared DynamicLinksExample.entitlements file.

[FDL] Fix SwiftUI quickstart Xcode project references

---

authentication/Podfile
authentication/Podfile.lock

Opened #1461 to track GSI 7 port

Restrict GoogleSignIn dependency to 6.x until we update to the 7.x API

---

messaging/MessagingExampleUITests/MessagingExampleUITests.m

Remove check for FCM Token in unit test for the Sample since a FCM Token now requires an APNS token to be specified. The unit test is meant to check if app launched successfully and existing check for sample app launch should be sufficient.

[Messaging] - Remove FCM Token Check from Unit Test for Sample

---

authentication/AuthenticationExample.xcodeproj/project.pbxproj
authentication/AuthenticationExample/Utility/CryptoUtils.swift
authentication/AuthenticationExample/ViewControllers/AccountLinkingViewController.swift
authentication/AuthenticationExample/ViewControllers/AuthViewController.swift
authentication/LegacyAuthQuickstart/AuthenticationExampleSwift/MainViewController.swift

The nonce generation we use in the sample (and correspondingly on the docs site) can be simplified. I gave it a go and came to the following solution. Any further feedback/alternative approaches welcome.
For more context, see https://github.com/firebase/firebase-ios-sdk/discussions/10732#discussion-4787797
```swift
// Adapted from https://auth0.com/docs/api-auth/tutorials/nonce#generate-a-cryptographically-random-nonce
private func randomNonceString(length: Int = 32) -> String {
precondition(length > 0)
let charset: [Character] =
Array("0123456789ABCDEFGHIJKLMNOPQRSTUVXYZabcdefghijklmnopqrstuvwxyz-._")
var result = ""
var remainingLength = length
while remainingLength > 0 {
let randoms: [UInt8] = (0 ..< 16).map { _ in
var random: UInt8 = 0
let errorCode = …
```

[Auth] Update 'randomNonceString' implementation

---

config/ConfigExample/RemoteConfigViewController.swift
config/README.md

This addresses two issues that I noticed when following the quickstart recently.
1) The config quickstart readme referenced recipeKey but the code referenced typedRecipeKey
2) The config only updated bottom label if it contained the word "one". I update it to always update the bottom label but to only perform text substitution for free count if the bottom label contains "one"

Update config quickstart to mention typedRecipeKey and to update bottomLabel

---

storage/StorageExample/StorageExample.xcodeproj/project.pbxproj

- Updated the Firebase Storage quickstart to depend on Firebase 10.x (previously set to 9.x)
- Changed the framework `FirebaseStorageSwift-Beta` to `FirebaseStorage` (this is the Swift implementation in 10.x)

Update Storage quickstart to depend on Firebase 10.x

---

abtesting/LegacyABTestingQuickstart/Podfile
admob/Podfile
analytics/LegacyAnalyticsQuickstart/Podfile
appdistribution/Podfile
authentication/LegacyAuthQuickstart/Podfile
config/LegacyConfigQuickstart/Podfile
crashlytics/LegacyCrashlyticsQuickstart/Podfile
database/Podfile
dynamiclinks/Podfile
functions/LegacyFunctionsQuickstart/Podfile
inappmessaging/Podfile
installations/Podfile
messaging/Podfile
performance/Podfile
storage/LegacyStorageQuickstart/Podfile
template/clone.sh

- New projects should have at least an iOS 13 minimum
- Prepare for integration testing for next major Firebase release that will require iOS 13

Update all quickstarts to iOS 13 minimum

---

.github/workflows/abtesting.yml
.github/workflows/admob.yml
.github/workflows/authentication.yml
.github/workflows/config.yml
.github/workflows/crashlytics.yml
.github/workflows/database.yml
.github/workflows/dynamiclinks.yml
.github/workflows/firestore.yml
.github/workflows/functions.yml
.github/workflows/inappmessaging.yml
.github/workflows/installations.yml
.github/workflows/messaging.yml
.github/workflows/performance.yml
.github/workflows/storage.yml
scripts/framework_test.sh
scripts/test.sh

Otherwise Xcode 15 doesn't work

Run on iPhone 14 instead of iPhone 11

---

storage/StorageExample/StorageExample.xcodeproj/project.pbxproj

Rather than use a version range, prefer `upToNextMajorVersion` so a single grep and replace can work for when we update QSs for a major version update.

[Storage] Standardize Firebase's dependency rules with other QS apps

---

.github/workflows/database.yml
.github/workflows/performance.yml

Xcode 13 is no longer supported so these TODOs about it are now irrelevant.

[NFC] Remove TODOs about Xcode 13

---

scripts/add_framework_script.rb

Locally this does embed frameworks when using the script.

[Infra] Embed frameworks `scripts/add_framework_script.rb`

---

scripts/add_framework_script.rb

Reverts firebase/quickstart-ios#1576

Revert "[Infra] Embed frameworks `scripts/add_framework_script.rb`"

---

scripts/add_framework_script.rb

By default, they are embedded to the `Resources` directory in the app bundle (which is at the root of the app). To mirror what zip customers would be doing, they should be embedded in the `Frameworks` directory. This didn't cause any errors, but likely would if we were shipping dynamic frameworks.

[Infra] Embed frameworks in Frameworks dir

---

scripts/add_framework_script.rb

Verified that running the script will setup the project in a way where the archives will be stripped out:
before:
```
‣ tree /Users/nickcooke/Library/Developer/Xcode/DerivedData/ABTestingExample-eiqvrjmoietiaeehlkxtcgcahmwq/Build/Products/Debug-iphoneos/ABTestingExample.app                                                      (75ms) 
/Users/nickcooke/Library/Developer/Xcode/DerivedData/ABTestingExample-eiqvrjmoietiaeehlkxtcgcahmwq/Build/Products/Debug-iphoneos/ABTestingExample.app
├── ABTestingExample
├── Base.lproj
│   ├── LaunchScreen.storyboardc
│   │   ├── 01J-lp-oVM-view-Ze5-6b-2t3.nib
│   │   ├── Info.plist
│   │   └── UIViewController-01J-lp-oVM.nib
│   └── Main.storyboardc
│       ├── BYZ-38-t0r-view-8bC-Xf-vdC.nib
│       ├── Info.plist
│       └── …
```

[Infra] Embed static frameworks with proper settings

---

.github/workflows/authentication.yml
authentication/AuthenticationExample/SceneDelegate.swift
authentication/AuthenticationExample/ViewControllers/OtherAuthMethodControllers/PasswordlessViewController.swift
authentication/Podfile
authentication/Podfile.lock
authentication/README.md

The Auth sample should depend on the FDL service but not the FDL SDK
Port changes from https://github.com/firebase/firebase-ios-sdk/pull/12864

Remove FDL SDK usage from Auth QS

---

.github/workflows/abtesting.yml
.github/workflows/admob.yml
.github/workflows/analytics.yml
.github/workflows/authentication.yml
.github/workflows/check.yml
.github/workflows/config.yml
.github/workflows/crashlytics.yml
.github/workflows/database.yml
.github/workflows/dynamiclinks.yml
.github/workflows/firestore.yml
.github/workflows/functions.yml
.github/workflows/inappmessaging.yml
.github/workflows/installations.yml
.github/workflows/messaging.yml
.github/workflows/performance.yml
.github/workflows/storage.yml
scripts/test.sh

Now that Firebase 10.25 (and the AppStore) require Xcode 15, update quickstart CI from Xcode 14 to 15.
Also
- Add concurrency cancellation
- Remove FirebaseFunctions cocoapods build that depends on deprecated Material
- Disable two other XCTest runs that fail, but not a high priority to fix

Update CI to Xcode 15 and macos-14

---

vertexai/README.md

Updated the Vertex AI README to link to https://github.com/firebase/firebase-ios-sdk/tree/main/FirebaseVertexAI/Sample now that it has been merged into `main` (https://github.com/firebase/firebase-ios-sdk/pull/12955).

[Vertex AI] Update README link to point to `main`

---

.github/workflows/config.yml
.github/workflows/crashlytics.yml
.github/workflows/database.yml
.github/workflows/dynamiclinks.yml
.github/workflows/performance.yml
.github/workflows/storage.yml
scripts/build-for-testing.sh
scripts/test.sh

Get CI green by dropping ObjC build schemes and leaving Swift ones and disabling flaky test runs while continuing to build.

Update to Xcode 15.4 for test scripts

---

firestore/FirestoreExample/RestaurantsTableViewController.swift

With Firebase 11 and FirebaseUI 14, importing AuthUI no longer transitively imports Auth.
See https://github.com/firebase/firebase-ios-sdk/actions/runs/10381722483/job/28746515460
and  https://github.com/firebase/FirebaseUI-iOS/issues/1196#issuecomment-2288141876

AuthAI no longer transitively imports Auth

---

.github/workflows/abtesting.yml
.github/workflows/admob.yml
.github/workflows/analytics.yml
.github/workflows/authentication.yml
.github/workflows/check.yml
.github/workflows/config.yml
.github/workflows/crashlytics.yml
.github/workflows/database.yml
.github/workflows/dynamiclinks.yml
.github/workflows/firestore.yml
.github/workflows/functions.yml
.github/workflows/inappmessaging.yml
.github/workflows/installations.yml
.github/workflows/messaging.yml
.github/workflows/performance.yml
.github/workflows/storage.yml
scripts/build-for-testing.sh
scripts/framework_test.sh
scripts/test.sh

Updated the CI workflows to use `macos-15`, `Xcode_16.1` and the `iPhone 16` simulator. Xcode 16.x is no longer available in `macos-14` GitHub runner images (https://github.com/actions/runner-images/issues/10703).

Run CI on macOS 15 with the iPhone 16 simulator

---

scripts/build-for-testing.sh

Updated `build-for-testing.sh` to use Xcode 15.3. This is the current version supported by FTL:
This was increased to Xcode 16.1 in https://github.com/firebase/quickstart-ios/pull/1630 but tests are [currently failing](https://github.com/firebase/firebase-ios-sdk/actions/runs/11774435049/job/32792985360).

Run build-for-testing.sh on Xcode 15.3 to match FTL

---

scripts/test.sh

Updated `test.sh` to select Xcode 16.1 if the `/Applications/Xcode_16.1.app` directory exists, otherwise defaults to Xcode 15.3 (picked to match FTL https://github.com/firebase/quickstart-ios/pull/1651); if neither are available, CI will fail. The default iPhone simulator version is selected to match Xcode.

[CI] Select Xcode and Simulator version based available version

---

vertexai/ImagenScreen/ImagenScreen.swift
vertexai/ImagenScreen/ImagenViewModel.swift

- use the reusable `InputField` component for unified look and feel across samples
- lay out the images in a 2x2 grid
- use rounded corners
- add a progress overlay
- allow users to cancel the image generation process

Styled Imagen UI

---

firebaseai/FirebaseAIExample.xcodeproj/project.pbxproj

Updated the bundle ID to `com.google.firebase.quickstart.FirebaseAIExample` to follow the pattern of the other quickstarts and removed the dependency on the `FirebaseVertexAI` framework.

[Firebase AI] Update bundle ID and remove FirebaseVertexAI dep

---

firebaseai/FirebaseAIExample.xcodeproj/project.pbxproj
firebaseai/FirebaseAISample/ContentView.swift
firebaseai/GenerativeAITextSample/Screens/GenerateContentScreen.swift
firebaseai/GenerativeAITextSample/ViewModels/GenerateContentViewModel.swift

Make the sample easier for developers to experiment with generateContent API

Switch Summarize sample to Generate Content sample

---

firebaseai/FirebaseAISample/ContentView.swift

Renames the UI options for selecting the AI backend in the Firebase AI sample app.
- "Google AI" is changed to "Gemini Developer API"
- "Vertex AI" is changed to "Vertex AI Gemini API"
This aligns the UI with the latest product branding. The underlying enum cases (`googleAI`, `vertexAI`) and their mapping to the backend services remain unchanged.

Update Firebase AI backend selection strings

---

.github/workflows/firebaseai.yml

Fix for https://github.com/firebase/quickstart-ios/actions/runs/14877284690
firebase-ios-sdk `main`'s Package.swift is pointing to an unreleased FirebaseAnalytics

[firebaseai] Fix SPM build for pre-released analytics

---

.github/workflows/firebaseai.yml
firebaseai/FirebaseAIExample.xcodeproj/project.pbxproj
firebaseai/README.md

Updated the Firebase AI quickstart to use the tagged release of `firebase-ios-sdk` for the SPM dependency (up to next major version) instead of depending on `main`.

[Firebase AI] Switch to SemVer tagged `firebase-ios-sdk`

---

database/Podfile
database/Podfile.lock
firestore/Podfile
firestore/Podfile.lock
functions/LegacyFunctionsQuickstart/Podfile
functions/LegacyFunctionsQuickstart/Podfile.lock

Unrelated to access tokens, but the only thing keeping firebase-ios-sdk `prerelease` and `release` workflows from passing at this point.

[Infra] Upgrade to FirebaseUI v15

---

firebaseai/GenerativeAITextExample/Screens/GenerateContentScreen.swift

All original features of GenerativeAITextExample are preserved. To modify the input field’s style, simply update the InputField component, ensuring a consistent user experience.

[FirebaseAI] Use InputField component in GenerativeAITextExample

---

scripts/test.sh

Updated `test.sh` to remove the logic for Xcode 15, which is no longer supported.

[CI] Remove Xcode 15 support from `test.sh`

---

firebaseai/FirebaseAIExample.xcodeproj/project.pbxproj

Upgraded the `swift-markdown-ui` dependency from https://github.com/gonzalezreal/swift-markdown-ui/releases/tag/2.4.0 to https://github.com/gonzalezreal/swift-markdown-ui/releases/tag/2.4.1.

[Firebase AI] Upgrade `swift-markdown-ui` dependency
